# Generated by Django 4.2.1 on 2023-08-08 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('Usuario', 'Usuario'), ('Funcionario', 'Funcionario'), ('Administrador', 'Administrado')], max_length=100, null=True, verbose_name='Tipo Usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome de exibição')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True, verbose_name='Número de Telefone')),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Gênero')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_acces', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
