# Generated by Django 4.2.1 on 2023-08-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_create', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='username',
        ),
    ]
