# Generated by Django 4.2.1 on 2023-08-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_create', '0003_rename_nickname_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
