# Generated by Django 4.2.1 on 2023-08-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_create', '0005_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
