# Generated by Django 4.2.1 on 2023-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_create', '0007_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_img', verbose_name='Profile Image'),
        ),
    ]
